-- Clear existing data
DELETE FROM projects;

-- Insert sample projects with correct categories
INSERT INTO projects (
  title, title_ko, title_en, title_zh,
  description, description_ko, description_en, description_zh,
  category, funding_type, amount,
  youtube_url_1, youtube_url_2,
  text_info, text_info_ko, text_info_en, text_info_zh
) VALUES 
(
  '유료 설명 토론 경기장 플랫폼',
  '유료 설명 토론 경기장 플랫폼',
  'Paid Real-Name Debate Arena Platform',
  '付费实名辩论竞技场平台',
  '건강한 토론 문화를 만들어냅니다',
  '건강한 토론 문화를 만들어냅니다',
  'Creating a healthy debate culture',
  '创造健康的辩论文化',
  '웹플랫폼',
  'investment',
  200000,
  'https://www.youtube.com/shorts/SoGQzRd31Ef',
  'https://www.youtube.com/shorts/BhUaqmcEL4f',
  '실명 토론 플랫폼으로 건전한 토론 문화를 조성합니다',
  '실명 토론 플랫폼으로 건전한 토론 문화를 조성합니다',
  'Real-name debate platform to foster healthy discussion culture',
  '实名辩论平台培育健康讨论文化'
),
(
  '여행 숙박 플랫폼 Tourlt',
  '여행 숙박 플랫폼 Tourlt',
  'Travel Accommodation Platform Tourlt',
  '旅行住宿平台 Tourlt',
  '당신만을 위한 특별한 여행을 제공합니다',
  '당신만을 위한 특별한 여행을 제공합니다',
  'Providing special trips just for you',
  '为您提供专属特别旅行',
  'O2O',
  'investment',
  80000,
  'https://www.youtube.com/shorts/qav5Frczpnk',
  NULL,
  '개인 맞춤형 여행 숙박 서비스',
  '개인 맞춤형 여행 숙박 서비스',
  'Personalized travel accommodation service',
  '个性化旅行住宿服务'
),
(
  '전라도 수영분대 광장 콤보',
  '전라도 수영분대 광장 콤보',
  'Jeolla Swimming Team Plaza Combo',
  '全罗道游泳队广场组合',
  '전라도의 숨은 매력을 발견하는 특별한 여행',
  '전라도의 숨은 매력을 발견하는 특별한 여행',
  'Special trip to discover the hidden charm of Jeolla-do',
  '发现全罗道隐藏魅力的特别旅行',
  '기타',
  'investment',
  120000,
  NULL,
  NULL,
  '전라도 지역 특화 관광 플랫폼',
  '전라도 지역 특화 관광 플랫폼',
  'Jeolla-do specialized tourism platform',
  '全罗道地区专业旅游平台'
),
(
  'AI 기반 서비스 온라인 분석',
  'AI 기반 서비스 온라인 분석',
  'AI-based Service Online Analysis',
  'AI驱动的服务在线分析',
  'AI가 실시간 데이터를 분석하여 서비스를 최적화합니다',
  'AI가 실시간 데이터를 분석하여 서비스를 최적화합니다',
  'AI analyzes real-time data to optimize services',
  'AI分析实时数据优化服务',
  '웹플랫폼',
  'donation',
  30000,
  NULL,
  NULL,
  'AI 기반 온라인 분석 서비스',
  'AI 기반 온라인 분석 서비스',
  'AI-based online analysis service',
  '基于AI的在线分析服务'
),
(
  '디지털 명함 Puke365',
  '디지털 명함 Puke365',
  'Digital Business Card Puke365',
  '数字名片 Puke365',
  '스마트한 디지털 명함으로 네트워킹 시작',
  '스마트한 디지털 명함으로 네트워킹 시작',
  'Start networking with smart digital business cards',
  '用智能数字名片开始人脉拓展',
  '게임',
  'startup',
  25000,
  NULL,
  NULL,
  '디지털 명함 교환 및 네트워킹 플랫폼',
  '디지털 명함 교환 및 네트워킹 플랫폼',
  'Digital business card exchange and networking platform',
  '数字名片交换及人脉拓展平台'
),
(
  '웰빙 AI 알림관리',
  '웰빙 AI 알림관리',
  'Wellness AI Notification Management',
  '健康AI通知管理',
  'AI가 실시간 알림으로 수면 패턴을 분석합니다',
  'AI가 실시간 알림으로 수면 패턴을 분석합니다',
  'AI analyzes sleep patterns with real-time notifications',
  'AI通过实时通知分析睡眠模式',
  'O2O',
  'investment',
  40000,
  NULL,
  NULL,
  'AI 기반 웰빙 관리 서비스',
  'AI 기반 웰빙 관리 서비스',
  'AI-based wellness management service',
  '基于AI的健康管理服务'
),
(
  '이룸 AI 게임 실시간탐색 가치데모 시연',
  '이룸 AI 게임 실시간탐색 가치데모 시연',
  'Ireum AI Game Real-time Exploration Demo',
  'Ireum AI游戏实时探索演示',
  '이룸에서 궁중한 실험을 주력으로 만듭니다',
  '이룸에서 궁중한 실험을 주력으로 만듭니다',
  'Making serious experiments the main focus at Ireum',
  '在Ireum将严肃实验作为主要重点',
  '게임',
  'donation',
  150000,
  NULL,
  NULL,
  'AI 게임 실시간 탐색 기술 데모',
  'AI 게임 실시간 탐색 기술 데모',
  'AI game real-time exploration technology demo',
  'AI游戏实时探索技术演示'
),
(
  '초소간 타비돔문 플랫폼',
  '초소간 타비돔문 플랫폼',
  'Minimal Time Window Platform',
  '极简时间窗口平台',
  '인공지능이 보급하는 맛집보유 일출 근무지 역을 조하 문아',
  '인공지능이 보급하는 맛집보유 일출 근무지 역을 조하 문아',
  'AI spreading restaurant possession sunrise workplace analysis',
  'AI传播餐厅占有日出工作场所分析',
  '기타',
  'donation',
  75000,
  NULL,
  NULL,
  'AI 기반 시간 관리 플랫폼',
  'AI 기반 시간 관리 플랫폼',
  'AI-based time management platform',
  '基于AI的时间管理平台'
),
(
  '만족하의 내열 플랫폼',
  '만족하의 내열 플랫폼',
  'Satisfaction Heat-Resistance Platform',
  '满意度耐热平台',
  '안전검과 투명한 맛집 만들기 가득 배송 서비스',
  '안전검과 투명한 맛집 만들기 가득 배송 서비스',
  'Safe and transparent restaurant making full delivery service',
  '安全透明的餐厅打造完整配送服务',
  '웹플랫폼',
  'investment',
  75000,
  NULL,
  NULL,
  '안전하고 투명한 배송 플랫폼',
  '안전하고 투명한 배송 플랫폼',
  'Safe and transparent delivery platform',
  '安全透明的配送平台'
),
(
  '만휨르 게이 전단 외국관광 패키지',
  '만휨르 게이 전단 외국관광 패키지',
  'Manheur Gay Flyer Foreign Tourism Package',
  'Manheur同性恋传单外国旅游套餐',
  '보건할 게이 전단 외국관광 서비스 만들기',
  '보건할 게이 전단 외국관광 서비스 만들기',
  'Creating health gay flyer foreign tourism service',
  '创建健康同性恋传单外国旅游服务',
  'O2O',
  'startup',
  100000,
  NULL,
  NULL,
  '외국인 관광객을 위한 패키지 서비스',
  '외국인 관광객을 위한 패키지 서비스',
  'Package service for foreign tourists',
  '为外国游客提供的套餐服务'
),
(
  '고인저동들 프로그램 cashiq.me 고개 본이 게임 서줬 only',
  '고인저동들 프로그램 cashiq.me 고개 본이 게임 서줬 only',
  'RIP Movement Program cashiq.me Customer Original Game Served only',
  '故人移动程序cashiq.me客户原创游戏仅提供',
  '고객시이 게링구 재작으로 자동화를 실행합니다',
  '고객시이 게링구 재작으로 자동화를 실행합니다',
  'Executing automation with customer gaming recreation',
  '通过客户游戏娱乐执行自动化',
  '기타',
  'investment',
  50000,
  NULL,
  NULL,
  '고객 맞춤형 게임 자동화 서비스',
  '고객 맞춤형 게임 자동화 서비스',
  'Customer-customized game automation service',
  '客户定制游戏自动化服务'
),
(
  '예충 일정관리',
  '예충 일정관리',
  'Budget Schedule Management',
  '预算日程管理',
  '예산 일정을 초월한는 노력영으로 습동맨빈다',
  '예산 일정을 초월한는 노력영으로 습동맨빈다',
  'Acquiring momentum through effort beyond budget schedule',
  '通过超越预算日程的努力获得动力',
  '선택',
  'startup',
  10000,
  NULL,
  NULL,
  '예산 및 일정 관리 서비스',
  '예산 및 일정 관리 서비스',
  'Budget and schedule management service',
  '预算及日程管理服务'
);
